version: "2.2"
services:
    smabdellah_php:
      image: php
      container_name: smabdellah_php
      restart: always
      volumes:
          - smabdellah_php_volume:/var/www/html/
          - /home/directory/
          - /home/directory/
      networks:
          - smabdellah_networks
      environment:
          VIRTUAL_HOST: smabdellah.dzshops.net
          LETSENCRYPT_HOST: smabdellah.dzshops.net
          mysqlpassword: rootpassword
          dbhost: smabdellah_mysql
    smabdellah_mysql:
      image: mysql
      container_name: smabdellah_mysql
      restart: always
      volumes:
          - smabdellah_mysql_volume:/var/lib/mysql/
          - /home/directory/
          - /home/directory/
      networks:
          - smabdellah_networks
      environment:
          nombreMagasin: "2"
          mysqlpassword: rootpassword
volumes:
  smabdellah_php_volume: 
  smabdellah_mysql_volume: 
networks:
  smabdellah_networks: 
